#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Compile data/scenarios/<name>.txt into binary scenario files (M4a, D22).

    uv run tools/gen_scenarios.py

Outputs (generated, not committed):
  build/scenarios/<name>.scn    loaded by the game from /loc/scenarios
  src/core/gen/scenarios.c      the same bytes as C arrays (selftest, host)

.scn format v1:
  "LOCS" | version | book_count
  | per book: owner u8 | entry_count u8 | entries: spell u8, level u8

The map itself is referenced by name only; the caller loads
maps/<map>.map. Spell ids come from the generated gen/data.h enum.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCN = ROOT / "data" / "scenarios"
OUT_DIR = ROOT / "build" / "scenarios"
OUT_C = ROOT / "src" / "core" / "gen" / "scenarios.c"
OUT_H = ROOT / "src" / "core" / "gen" / "scenarios.h"
CORE = ROOT / "src" / "core"

OWNERS = {"p1": 0, "p2": 1, "p3": 2, "p4": 3}


def spell_ids() -> dict[str, int]:
    """SP_* enumerator values from the generated header."""
    text = re.sub(r"/\*.*?\*/", "", (CORE / "gen" / "data.h").read_text(encoding="utf-8"),
                  flags=re.S)
    values: dict[str, int] = {}
    for body in re.findall(r"typedef enum \{([^}]*)\} SpellId;", text, flags=re.S):
        nxt = 0
        for item in body.split(","):
            item = item.strip()
            if not item:
                continue
            if "=" in item:
                name, val = (x.strip() for x in item.split("=", 1))
                nxt = int(val, 0)
            else:
                name = item
            values[name] = nxt
            nxt += 1
    return values


def parse(path: Path) -> dict:
    m: dict = {"map": None, "books": []}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        word, _, rest = line.partition(" ")
        if word == "map":
            m["map"] = rest.strip()
        elif word == "book":
            owner, _, entries = rest.strip().partition(" ")
            book = []
            for pair in entries.split(","):
                spell, _, level = pair.strip().partition(" ")
                book.append((spell, int(level)))
            m["books"].append((owner, book))
        else:
            raise SystemExit(f"{path.name}: unexpected line: {raw!r}")
    if not m["map"]:
        raise SystemExit(f"{path.name}: missing map line")
    return m


def encode(m: dict, ids: dict[str, int]) -> bytes:
    out = bytearray(b"LOCS")
    out.append(1)
    out.append(len(m["books"]))
    for owner, book in m["books"]:
        if owner not in OWNERS:
            raise SystemExit(f"unknown owner {owner!r}")
        out.append(OWNERS[owner])
        out.append(len(book))
        for spell, level in book:
            key = "SP_" + spell.upper()
            if key not in ids:
                raise SystemExit(f"unknown spell {spell!r} (see data/spells.csv)")
            if not 1 <= level <= 8:
                raise SystemExit(f"spell level must be 1..8: {spell} {level}")
            out.append(ids[key])
            out.append(level)
    return bytes(out)


def main() -> int:
    ids = spell_ids()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_C.parent.mkdir(parents=True, exist_ok=True)
    c = ["/* GENERATED by tools/gen_scenarios.py - do not edit. */",
         '#include "scenarios.h"', ""]
    names = []
    for path in sorted(SCN.glob("*.txt")):
        data = encode(parse(path), ids)
        out = OUT_DIR / (path.stem + ".scn")
        out.write_bytes(data)
        name = path.stem.upper()
        names.append(name)
        c.append(f"const uint8_t SCN_{name}[{len(data)}] = {{")
        c.append("    " + ", ".join(str(b) for b in data))
        c.append("};")
        c.append(f"const uint16_t SCN_{name}_LEN = {len(data)};")
        c.append("")
        print(f"[scn] {path.name} -> {out.relative_to(ROOT).as_posix()} ({len(data)} bytes)")
    h = ["/* GENERATED by tools/gen_scenarios.py - do not edit. */",
         "#ifndef LOC_GEN_SCENARIOS_H", "#define LOC_GEN_SCENARIOS_H", "",
         "#include <stdint.h>", ""]
    for n in names:
        h.append(f"extern const uint8_t SCN_{n}[];")
        h.append(f"extern const uint16_t SCN_{n}_LEN;")
    h += ["", "#endif", ""]
    (CORE / "gen" / "scenarios.h").write_text("\n".join(h), encoding="utf-8", newline="\n")
    OUT_C.write_text("\n".join(c), encoding="utf-8", newline="\n")
    print(f"[scn] {OUT_C.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
