#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Compile the rule tables data/*.csv into C (ADR 0008: small tables are built
into the binary; maps and tiles come from the SD card).

    uv run tools/gen_data.py

Outputs (generated, not committed): src/core/gen/data.h, src/core/gen/data.c
  - FLOOR_AP[FL_COUNT]          orthogonal AP per floor (data/costs.csv)
  - SpellDef SPELLS[SPELL_COUNT] name, category, mana formula (data/spells.csv)
  - ActionDef ACTIONS[ACT_COUNT] AP/stamina per action (data/actions.csv)
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT_H = ROOT / "src" / "core" / "gen" / "data.h"
OUT_C = ROOT / "src" / "core" / "gen" / "data.c"

# Which costs.csv row applies to each core floor type (world.h Floor order).
FLOOR_TERRAIN = [("FL_STONE", "floor"), ("FL_WOOD", "floor"),
                 ("FL_GRASS", "grass"), ("FL_PATH", "road")]
CATEGORIES = {"summon": "SPC_SUMMON", "potion": "SPC_POTION", "area": "SPC_AREA",
              "other": "SPC_OTHER"}


def rows(name: str) -> list[dict]:
    lines = [l for l in (DATA / name).read_text(encoding="utf-8").splitlines()
             if l.strip() and not l.startswith("#")]
    return list(csv.DictReader(lines))


def cstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    costs = {r["terrain"]: r for r in rows("costs.csv")}
    spells = rows("spells.csv")
    actions = rows("actions.csv")
    for r in spells:   # unknown values (e.g. Amiga bomb potion) -> 0, flagged
        r["known"] = "1" if r["mana_base"] else "0"
        r["mana_base"] = r["mana_base"] or "0"
        r["mana_step"] = r["mana_step"] or "0"

    h = ["/* GENERATED by tools/gen_data.py from data/<table>.csv - do not edit. */",
         "#ifndef LOC_GEN_DATA_H", "#define LOC_GEN_DATA_H", "",
         "#include <stdint.h>", "",
         '#include "../world.h"', "",
         "extern const uint8_t FLOOR_AP[FL_COUNT];", "",
         "typedef enum { " + ", ".join(CATEGORIES.values()) + " } SpellCategory;",
         "typedef enum {"]
    h += [f"    SP_{r['id'].upper()}," for r in spells]
    h += ["    SPELL_COUNT", "} SpellId;", "",
          "typedef struct {",
          "    const char *name;",
          "    uint8_t category;   /* SpellCategory */",
          "    uint8_t mana_base, mana_step;   /* mana(level) = base + level * step */",
          "    uint8_t amiga;      /* exists in the Amiga version */",
          "    uint8_t known;      /* mana values known (0: to be observed) */",
          "} SpellDef;",
          "extern const SpellDef SPELLS[SPELL_COUNT];", "",
          "typedef enum {"]
    h += [f"    ACT_{r['action'].upper()}," for r in actions]
    h += ["    ACT_COUNT", "} ActionId;", "",
          "typedef struct { uint8_t ap, stamina; } ActionDef;",
          "extern const ActionDef ACTIONS[ACT_COUNT];", "", "#endif", ""]

    c = ["/* GENERATED by tools/gen_data.py from data/<table>.csv - do not edit. */",
         '#include "data.h"', "",
         "const uint8_t FLOOR_AP[FL_COUNT] = {"]
    c += [f"    [{fl}] = {int(costs[t]['ap_orth'])},   /* {t} */" for fl, t in FLOOR_TERRAIN]
    c += ["};", "", "const SpellDef SPELLS[SPELL_COUNT] = {"]
    c += [f"    [SP_{r['id'].upper()}] = {{{cstr(r['name'])}, {CATEGORIES[r['category']]}, "
          f"{int(r['mana_base'])}, {int(r['mana_step'])}, {1 if r['amiga'] == 'yes' else 0}, "
          f"{r['known']}}}," for r in spells]
    c += ["};", "", "const ActionDef ACTIONS[ACT_COUNT] = {"]
    c += [f"    [ACT_{r['action'].upper()}] = {{{int(r['ap'])}, {int(r['stamina'])}}},"
          for r in actions]
    c += ["};", ""]

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(h), newline="\n")
    OUT_C.write_text("\n".join(c), newline="\n")
    print(f"[data] {len(spells)} spells, {len(actions)} actions, {len(FLOOR_TERRAIN)} floors "
          f"-> src/core/gen/data.[ch]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
