#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Compile data/maps/<name>.txt into src/core/gen/maps.c (generated, not committed).

    uv run tools/gen_maps.py

The map text format is documented at the top of data/maps/wizard_house.txt.
Character legends are validated here; the C side (src/core/world.c) maps the
characters to floor/feature/decor types.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAPS = ROOT / "data" / "maps"
OUT = ROOT / "src" / "core" / "gen" / "maps.c"

FLOOR_CHARS = set("swgp")
FEATURE_CHARS = set(".#DdBSKCThMXt")
DECOR_CHARS = set(".r*")
KINDS = {"wizard": "CR_WIZARD", "goblin": "CR_GOBLIN"}
OWNERS = {"p1": "OWN_P1", "p2": "OWN_P2", "p3": "OWN_P3", "p4": "OWN_P4", "neutral": "OWN_NEUTRAL"}


def parse(path: Path) -> dict:
    m = {"wrap": 0, "units": [], "objects": []}
    section = None
    grids: dict[str, list[str]] = {"floor": [], "feature": [], "decor": []}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].rstrip() if not section in grids else raw.rstrip()
        if section in grids and line.startswith("#") and not set(line) <= FEATURE_CHARS:
            continue
        if not line.strip():
            section = None if section in grids and grids[section] else section
            continue
        word = line.split()[0]
        if word == "size":
            m["w"], m["h"] = map(int, line.split()[1:3])
        elif word == "wrap":
            m["wrap"] = int(line.split()[1])
        elif word in ("floor", "feature", "decor", "units", "objects") and len(line.split()) == 1:
            section = word
        elif section in grids:
            grids[section].append(line)
        elif section == "units":
            x, y, kind, owner = line.split()
            m["units"].append((int(x), int(y), KINDS[kind], OWNERS[owner]))
        elif section == "objects":
            x, y, name = line.split()
            m["objects"].append((int(x), int(y), "T_" + name.upper()))
        else:
            raise SystemExit(f"{path.name}: unexpected line: {raw!r}")
    for key, chars in (("floor", FLOOR_CHARS), ("feature", FEATURE_CHARS), ("decor", DECOR_CHARS)):
        rows = grids[key]
        if len(rows) != m["h"] or any(len(r) != m["w"] for r in rows):
            raise SystemExit(f"{path.name}: {key} must be {m['w']}x{m['h']}")
        bad = set("".join(rows)) - chars
        if bad:
            raise SystemExit(f"{path.name}: {key} has unknown characters {sorted(bad)}")
        m[key] = "".join(rows)
    return m


def c_name(path: Path) -> str:
    return "MAP_" + re.sub(r"\W", "_", path.stem).upper()


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out = ["/* GENERATED by tools/gen_maps.py from data/maps/<name>.txt - do not edit. */",
           '#include "../map_def.h"', '#include "tiles.h"', ""]
    for path in sorted(MAPS.glob("*.txt")):
        m = parse(path)
        n = c_name(path)
        units = ", ".join(f"{{{x}, {y}, {k}, {o}}}" for x, y, k, o in m["units"])
        objs = ", ".join(f"{{{x}, {y}, {t}}}" for x, y, t in m["objects"])
        out += [
            f"static const MapUnit {n}_units[] = {{{units}}};",
            f"static const MapObject {n}_objects[] = {{{objs}}};",
            f"const MapDef {n} = {{",
            f"    {m['w']}, {m['h']}, {m['wrap']},",
            f'    "{m["floor"]}",',
            f'    "{m["feature"]}",',
            f'    "{m["decor"]}",',
            f"    {n}_units, {len(m['units'])},",
            f"    {n}_objects, {len(m['objects'])},",
            "};", "",
        ]
        print(f"[maps] {path.name} -> {n} ({m['w']}x{m['h']}, {len(m['units'])} units)")
    OUT.write_text("\n".join(out), newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
