#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Compile the rule tables data/*.csv into C (ADR 0008: small tables are built
into the binary; maps and tiles come from the SD card).

    uv run tools/gen_data.py

Outputs (generated, not committed): src/core/gen/data.h, src/core/gen/data.c
  - FLOOR_AP[FL_COUNT]          orthogonal AP per floor (data/costs.csv)
  - SpellDef SPELLS[SPELL_COUNT] name, category, mana formula (data/spells.csv)
  - ActionDef ACTIONS[ACT_COUNT] AP/stamina per action (data/actions.csv)
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT_H = ROOT / "src" / "core" / "gen" / "data.h"
OUT_C = ROOT / "src" / "core" / "gen" / "data.c"
OUT_CR = ROOT / "src" / "core" / "gen" / "creatures.h"

# Which costs.csv row applies to each core floor type (world.h Floor order).
FLOOR_TERRAIN = [("FL_STONE", "floor"), ("FL_WOOD", "floor"), ("FL_GRASS", "grass"),
                 ("FL_PATH", "road"), ("FL_TALL_GRASS", "tall_grass"), ("FL_FOREST", "forest"),
                 ("FL_MAGIC_WOOD", "magic_wood"), ("FL_SHADOW_WOOD", "shadow_wood"),
                 ("FL_SWAMP", "swamp"), ("FL_WATER", "water"), ("FL_RUBBLE", "rubble")]
NATIVE = {"": "0", "wood": "NATIVE_WOOD", "water": "NATIVE_WATER", "rock": "NATIVE_ROCK"}
CATEGORIES = {"summon": "SPC_SUMMON", "potion": "SPC_POTION", "area": "SPC_AREA",
              "other": "SPC_OTHER"}


def rows(name: str) -> list[dict]:
    lines = [l for l in (DATA / name).read_text(encoding="utf-8").splitlines()
             if l.strip() and not l.startswith("#")]
    return list(csv.DictReader(lines))


def cstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    costs = {r["terrain"]: r for r in rows("costs.csv")}
    features = {r["id"]: r for r in rows("features.csv")}
    objects = rows("objects.csv")
    weapons = rows("weapons.csv")
    spells = rows("spells.csv")
    creatures = rows("creatures.csv")
    actions = rows("actions.csv")
    for r in spells:   # unknown values (e.g. Amiga bomb potion) -> 0, flagged
        r["known"] = "1" if r["mana_base"] else "0"
        r["mana_base"] = r["mana_base"] or "0"
        r["mana_step"] = r["mana_step"] or "0"

    h = ["/* GENERATED by tools/gen_data.py from data/<table>.csv - do not edit. */",
         "#ifndef LOC_GEN_DATA_H", "#define LOC_GEN_DATA_H", "",
         "#include <stdint.h>", "",
         '#include "../world.h"', "",
         "extern const uint8_t FLOOR_AP[FL_COUNT];",
         "extern const uint8_t FLOOR_SIGHT[FL_COUNT];   /* blocks ground sight */",
         "enum { NATIVE_WOOD = 1, NATIVE_WATER = 2, NATIVE_ROCK = 4 };",
         "extern const uint8_t FLOOR_NATIVE[FL_COUNT];  /* creature type paying floor cost */",
         "extern const uint8_t FLOOR_DROWN[FL_COUNT];   /* drowning check for non-natives */",
         "extern const uint8_t FEATURE_TOUGH[FE_COUNT];  /* melee hits a feature survives (0: no/never) */",
         "/* Flying movement (costs.csv row air): constant, whatever is below. */",
         f"enum {{ AIR_AP_ORTH = {int(costs['air']['ap_orth'])}, AIR_AP_DIAG = {int(costs['air']['ap_diag'])} }};", "",
         "typedef enum { " + ", ".join(CATEGORIES.values()) + " } SpellCategory;",
         "typedef enum {"]
    h += [f"    SP_{r['id'].upper()}," for r in spells]
    h += ["    SPELL_COUNT", "} SpellId;", "",
          "typedef enum {"]
    h += [f"    OBJ_{r['id'].upper()}," for r in objects]
    h += ["    OBJ_COUNT", "} ObjectKind;", ""]
    h += ["typedef struct {",
          "    const char *name;",
          "    uint8_t category;   /* SpellCategory */",
          "    uint8_t mana_base, mana_step;   /* mana(level) = base + level * step */",
          "    uint8_t amiga;      /* exists in the Amiga version */",
          "    uint8_t known;      /* mana values known (0: to be observed) */",
          "} SpellDef;",
          "extern const SpellDef SPELLS[SPELL_COUNT];", "",
          "typedef enum {"]
    h += [f"    ACT_{r['action'].upper()}," for r in actions]
    h += ["    ACT_COUNT", "} ActionId;", "",
          "typedef struct { uint8_t ap, stamina; } ActionDef;",
          "extern const ActionDef ACTIONS[ACT_COUNT];", "",
          "enum { CF_MOUNT = 1, CF_RIDE = 2, CF_UNDEAD = 4, CF_WEAPONS = 8, CF_USE = 16 };",
          "typedef struct {",
          "    const char *name;",
          "    uint8_t ap, ap_fly, stamina, con, combat, defence, magic_res;",
          "    uint8_t carry, potion, vp, mana;",
          "    uint8_t flags;    /* CF_* */",
          "    uint8_t native;   /* NATIVE_* terrain type */",
          "} CreatureDef;",
          "extern const CreatureDef CREATURES[CR_COUNT];",
          "/* Tile of the p1 variant; + Owner gives the owner colour (GDD 11.2). */",
          "extern const uint16_t CREATURE_TILE[CR_COUNT];",
         "/* Creature kind a summon spell calls (0xFF: no summon), by equal id. */",
         "extern const uint8_t SUMMON_KIND[SPELL_COUNT];",
         "typedef struct { const char *name; uint8_t combat, defence, thrown,",
         "                  ranged, weight; } WeaponDef;",
         "enum { WEAPON_SWORD, WEAPON_KNIFE, WEAPON_SHIELD, WEAPON_BOW, WEAPON_SPEAR,",
         "       WEAPON_CLUB, WEAPON_AXE, WEAPON_NINJA_STAR, WEAPON_SLAYER,",
         "       WEAPON_MAGIC_SLAYER, WEAPON_COUNT };",
         "#define WEAPON_NONE 0xFF",
         "extern const WeaponDef WEAPONS[WEAPON_COUNT];",
         "enum { OC_WEAPON, OC_TREASURE, OC_SCROLL, OC_FOOD, OC_KEY, OC_POTION, OC_INGREDIENT };",
         "typedef struct { const char *name; uint8_t category, weight, vp, weapon;",
         "                  uint8_t eat_con, eat_mana;   /* food values (GDD 8) */"
         " uint16_t tile; } ObjectDef;",
         "extern const ObjectDef OBJECTS[OBJ_COUNT];",
         "", "#endif", ""]

    c = ["/* GENERATED by tools/gen_data.py from data/<table>.csv - do not edit. */",
         '#include "data.h"', '#include "tiles.h"', "",
         "const uint8_t FLOOR_AP[FL_COUNT] = {"]
    c += [f"    [{fl}] = {int(costs[t]['ap_orth'])},   /* {t} */" for fl, t in FLOOR_TERRAIN]
    c += ["};", "", "const uint8_t FLOOR_SIGHT[FL_COUNT] = {"]
    c += [f"    [{fl}] = {1 if costs[t]['blocks_sight_ground'] == 'yes' else 0}," for fl, t in FLOOR_TERRAIN]
    c += ["};", "", "const uint8_t FLOOR_NATIVE[FL_COUNT] = {"]
    c += [f"    [{fl}] = {NATIVE[costs[t]['native']]}," for fl, t in FLOOR_TERRAIN]
    c += ["};", "", "const uint8_t FLOOR_DROWN[FL_COUNT] = {"]
    c += [f"    [{fl}] = {1 if costs[t]['hazard'] == 'drown' else 0}," for fl, t in FLOOR_TERRAIN]
    c += ["};", "",
          "const uint8_t FEATURE_TOUGH[FE_COUNT] = {"]
    feat_ids = ["none", "wall", "door_closed", "door_open", "bed", "bookshelf",
                "candle", "cauldron", "table", "chair", "drawers", "chest",
                "tree", "rock"]
    assert set(feat_ids) == set(features), sorted(set(feat_ids) ^ set(features))
    c += [f"    [{i}] = {int(features[f]['toughness'])},   /* {f} */"
          for i, f in enumerate(feat_ids)]
    c += ["};", "", "const SpellDef SPELLS[SPELL_COUNT] = {"]
    c += [f"    [SP_{r['id'].upper()}] = {{{cstr(r['name'])}, {CATEGORIES[r['category']]}, "
          f"{int(r['mana_base'])}, {int(r['mana_step'])}, {1 if r['amiga'] == 'yes' else 0}, "
          f"{r['known']}}}," for r in spells]
    c += ["};", "",
          "const uint8_t SUMMON_KIND[SPELL_COUNT] = {"]
    creature_ids = [r["id"] for r in creatures]
    for r in spells:
        if r["category"] == "summon":
            assert r["id"] in creature_ids, r["id"]
            c.append(f"    [SP_{r['id'].upper()}] = {creature_ids.index(r['id'])},")
        else:
            c.append(f"    [SP_{r['id'].upper()}] = 0xFF,")
    c += ["};", "",
          "const WeaponDef WEAPONS[WEAPON_COUNT] = {"]
    c += [f"    [WEAPON_{r['id'].upper()}] = {{{cstr(r['name'])}, {int(r['combat'])}, "
          f"{int(r['defence'])}, {int(r['thrown'])}, {int(r['ranged'])}, {int(r['weight'])}}},"
          for r in weapons]
    c += ["};", "",
          "const ObjectDef OBJECTS[OBJ_COUNT] = {"]
    for r in objects:
        w = "WEAPON_NONE" if r["category"] != "weapon" else "WEAPON_" + r["id"].upper()
        c.append(f"    [OBJ_{r['id'].upper()}] = {{{cstr(r['name'])}, "
                 f"{'OC_' + r['category'].upper()}, {int(r['weight'])}, {int(r['vp'])}, "
                 f"{w}, {int(r['eat_con'])}, {int(r['eat_mana'])}, "
                 f"T_{r['tile'].upper()}}},")
    c += ["};", "", "const ActionDef ACTIONS[ACT_COUNT] = {"]
    c += [f"    [ACT_{r['action'].upper()}] = {{{int(r['ap'])}, {int(r['stamina'])}}},"
          for r in actions]
    c += ["};", "", "const CreatureDef CREATURES[CR_COUNT] = {"]
    yes = lambda r, k: r[k] == "yes"
    for r in creatures:
        fl = [f for f, k in (("CF_MOUNT", "mount"), ("CF_RIDE", "ride"), ("CF_UNDEAD", "undead"),
                             ("CF_WEAPONS", "weapons"), ("CF_USE", "use")) if yes(r, k)]
        nat = [f for f, k in (("NATIVE_WOOD", "wood"), ("NATIVE_WATER", "water"),
                              ("NATIVE_ROCK", "rock")) if yes(r, k)]
        nums = ", ".join(r[k] for k in ("ap_ground", "ap_fly", "stamina", "constitution", "combat",
                                        "defence", "magic_res", "carry", "potion", "vp", "mana"))
        c.append(f"    [CR_{r['id'].upper()}] = {{{cstr(r['name'])}, {nums}, "
                 f"{' | '.join(fl) or '0'}, {' | '.join(nat) or '0'}}},")
    c += ["};", "", "const uint16_t CREATURE_TILE[CR_COUNT] = {"]
    c += [f"    [CR_{r['id'].upper()}] = T_{r['id'].upper()}_P1," for r in creatures]
    c += ["};", ""]
    cr = ["/* GENERATED by tools/gen_data.py from data/creatures.csv - do not edit. */",
          "#ifndef LOC_GEN_CREATURES_H", "#define LOC_GEN_CREATURES_H", "", "typedef enum {"]
    cr += [f"    CR_{r['id'].upper()}," for r in creatures]
    cr += ["    CR_COUNT", "} CreatureKind;", "", "#endif", ""]

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_CR.write_text("\n".join(cr), newline="\n")
    OUT_H.write_text("\n".join(h), newline="\n")
    OUT_C.write_text("\n".join(c), newline="\n")
    print(f"[data] {len(creatures)} creatures, {len(spells)} spells, {len(actions)} actions, "
          f"{len(FLOOR_TERRAIN)} floors "
          f"-> src/core/gen/data.[ch]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
